# -*- coding: utf-8 -*-
"""Programming Assignment_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1opUhtyNR8Nu0Gu6x_asN-YjJNOw8elii

# Programming Basic Assignment 6

------------
### 1. Write a Python Program to Display Fibonacci Sequence Using Recursion?
"""

def fibo(a,b,c):
    if c > 0:
        c -= 1
        print(a, end=' ')
        temp = b
        b = a + b
        a = temp
        fibo(a,b,c)

fibo(0,1,10)

"""-------------------
### 2. Write a Python Program to Find Factorial of Number Using Recursion?
"""

def fact(n):
    if n == 0:
        return 1
    else:
        return n*fact(n-1)

fact(5)

fact(7)

"""-------------
### 3. Write a Python Program to calculate your Body Mass Index?
"""

def bmi(height, weight):
    
    return weight/(height*height)

bmi(1.8, 70)

"""--------------
### 4. Write a Python Program to calculate the natural logarithm of any number?
"""

import math

try:
    num = int(input("Enter the number: "))
except Exception as e:
    print(e)
else:
    print(math.log(num))

"""------------
### 5. Write a Python Program for cube sum of first n natural numbers?

"""

def cubN(n):
    return sum(range(n+1))**3

cubN(3)

cubN(4)

